language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t complex-react-app -f ./client/Dockerfile.dev ./client 

script: 
  - docker run -e CI=true complex-react-app npm test

after_success: 
  - docker build -t abhinavsjalawadi/multi-client ./client
  - docker build -t abhinavsjalawadi/multi-nginx ./nginx
  - docker build -t abhinavsjalawadi/multi-server ./server
  - docker build -t abhinavsjalawadi/multi-worker ./worker

# Login to the Docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#Take those images and push to docker hub
  - docker push abhinavsjalawadi/multi-client
  - docker push abhinavsjalawadi/multi-nginx
  - docker push abhinavsjalawadi/multi-server
  - docker push abhinavsjalawadi/multi-worker